# Scaffolding generated by Casein v5.1.1.5

module Casein
  class JobClassesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Job classes'
  		@job_classes = JobClass.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View job class'
      @job_class = JobClass.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new job class'
    	@job_class = JobClass.new
    end

    def create
      @job_class = JobClass.new job_class_params
    
      if @job_class.save
        flash[:notice] = 'Job class created'
        redirect_to casein_job_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new job class'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update job class'
      
      @job_class = JobClass.find params[:id]
    
      if @job_class.update_attributes job_class_params
        flash[:notice] = 'Job class has been updated'
        redirect_to casein_job_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this job class'
        render :action => :show
      end
    end
 
    def destroy
      @job_class = JobClass.find params[:id]

      @job_class.destroy
      flash[:notice] = 'Job class has been deleted'
      redirect_to casein_job_classes_path
    end
  
    private
      
      def job_class_params
        params.require(:job_class).permit(:name, :caster, :saving_throws, :skill_proficiencies, :hit_dice, :armor_proficiencies, :weapon_proficiencies, :tool_proficiencies, :equipment, :level_1_features, :level_2_features, :level_3_features, :level_4_features, :level_5_features, :level_6_features, :level_7_features, :level_8_features, :level_9_features, :level_10_features, :level_11_features, :level_12_features, :level_13_features, :level_14_features, :level_15_features, :level_16_features, :level_17_features, :level_18_features, :level_19_features, :level_20_features, ability_ids:[], skill_ids:[])
      end

  end
end